### ISSUE TITLE
Spurious "This element has an unsupported ARIA attribute"

### ISSUE THREAD

**Issue by calebegg** [GoogleChrome/accessibility-developer-tools-extension#34]
<div aria-hidden="true">Test</div> gives a "[Severe] This element has an unsupported ARIA attribute". Spec says that aria-hidden is usable on "All elements of the base markup"

http://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden

Same for several others; aria-label, aria-disabled, etc.

**Comment by michelhebert** [comment]
I have the exact same problem since the last update.  Add to the list **aria-live**.

**Comment by RickSBrown** [comment]
Thanks for reporting.
This was fixed here: https://github.com/GoogleChrome/accessibility-developer-tools/issues/199
The fix should be included in the next release of the extension.

**Comment by alice** [comment]
This should be fixed in extension v2.10.9 which I just pushed out - please re-open if it isn't!
